version: '3.3'

services:
  poi:
    image: poi
    container_name: poi
    links:
      - sqlserver
    networks:
      - openhack
    environment:
      - ASPNETCORE_ENVIRONMENT=Local # Disable SSL
      # - ASPNETCORE_ENVIRONMENT="Development"
      - SQL_SERVER=sqlserver
      - SQL_USER=SA
      - SQL_PASSWORD=OpenHack12345
      - SQL_DBNAME=mydrivingDB
      - WEB_PORT=80
      - CONFIG_FILES_PATH="/secrets"
      # - WEB_SERVER_BASE_URI="http://0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://0.0.0.0:8080/api/poi/healthcheck"]
      interval: 60s
      timeout: 3s
      retries: 60
    ports:
      - 8080:80
    expose:
      - 80

  # run this to create db:
  # docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "OpenHack12345" -Q 'CREATE DATABASE mydrivingDB'
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    hostname: sqlserver
    networks:
      - openhack
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OpenHack12345
    ports:
      - 1433:1433
    expose:
      - 1433

  dataload:
    image: openhack/data-load:v1
    container_name: dataload
    networks:
      - openhack
    links:
      - sqlserver
    environment:
      - SQLFQDN=sqlserver
      - SQLUSER=SA
      - SQLPASS=OpenHack12345
      - SQLDB=mydrivingDB

networks:
  openhack:
    external:
      name: openhack
